name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    # Add your deployment steps here
    # Example for Railway:
    # - name: Deploy to Railway
    #   uses: railway-app/railway@v1
    #   with:
    #     railway_token: ${{ secrets.RAILWAY_TOKEN }}
    
    # Example for Render:
    # - name: Deploy to Render
    #   run: |
    #     curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
    
    # Example for custom server deployment:
    # - name: Deploy to server
    #   uses: appleboy/ssh-action@v1.0.0
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     script: |
    #       cd /path/to/app
    #       git pull
    #       npm ci
    #       npm run build
    #       pm2 restart app